language: go
go:
    - 1.9

install:
    - wget https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip
    - unzip packer_1.2.1_linux_amd64.zip 
    - sudo mv packer /usr/bin

script:
    - cd packer-test && ./test.sh

