language: go
go:
    - 1.9

install:
    - wget https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip
    - unzip packer_1.2.1_linux_amd64.zip 
    - sudo mv packer /usr/bin
    - cd packer-test && GIT_BRANCH=$(git rev-parse --abrev-ref HEAD) packer build ci-fast.sh
     #- cd ..
     #- cd /tmp 
     #- mkdir protobuf
     #- wget -P /tmp/protobuf https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip 
     #- cd protobuf
     #- unzip protoc-3.5.0-linux-x86_64.zip
     #- ls /tmp/protobuf/bin
     #- sudo mv /tmp/protobuf/bin/protoc /bin
     #- cd $GOPATH/src/github.com/anxiousmodernman/hpt && mkdir vendor
     #- cd $GOPATH/src/github.com/anxiousmodernman/hpt && dep ensure
     #- cd $GOPATH/src/github.com/anxiousmodernman/hpt && ./gen.sh
     #- cd $GOPATH/src/github.com/anxiousmodernman/hpt && go build

script:
    - go test -v ./...

