language: go
go:
    - 1.9

install:
    - go get -u github.com/golang/dep/cmd/dep
    - cd ..
    - cd /tmp 
    - mkdir protobuf
    - wget -P /tmp/protobuf https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-linux-x86_64.zip 
    - cd protobuf
    - unzip protoc-3.5.0-linux-x86_64.zip
    - ls /tmp/protobuf/bin
    - sudo mv /tmp/protobuf/bin/protoc /bin
    - cd $GOPATH/src/github.com/anxiousmodernman/hpt && dep ensure
    - cd $GOPATH/src/github.com/anxiousmodernman/hpt && ./gen.sh
    - cd $GOPATH/src/github.com/anxiousmodernman/hpt && go build

script:
    - go test -v ./...

