
packages = ["git", "wget"]

# Rework this DSL.
# [bucket.bkt]
# url = "nyc3.digitaloceanspaces.com"
# name = "coleman"

# [[file]]
# path = "/home/coleman/.ssh/hackbox"
# source = "bkt://ssh-keys/hackbox"
# perms = 600
# owner = "coleman"
# group = "coleman"


[[clone]]
URL = "https://github.com/anxiousmodernman/hpt.git"
dest = "/opt/hpt"

# install go 
[[exec]]
script = '''
rm -rf /usr/local/go
wget https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.9.1.linux-amd64.tar.gz
'''

# test hpt
[[exec]]
script = "/usr/local/go/bin/go test ./..."
dir = "/opt/hpt"

