secret = 100

[bucket.bucket1]
url = "nyc3.digitaloceanspaces.com"
name = "coleman"

[bucket.bucket2]
url = "nyc3.digitaloceanspaces.com"
name = "coleman2"

[repo.somerepo]
url = "https://github.com/foo/configs.git"

[[user]]
name = "coleman"
home = "/home/coleman"
groups = ["wheel", "something"]
ssh_public_key = "bucket1://ssh-keys/hackbox.pub"


