
#packages = ["epel-release", "git", "gcc", "libevent-devel", 
#            "automake", "ncurses-devel", "wget", "cmake", "gcc-c++",
#            "libtool", "unzip"]

packages = ["git", "wget"]

[bucket.bkt]
url = "nyc3.digitaloceanspaces.com"
name = "coleman"

[[group]]
name = "wheel"
passwordless_sudo = true

[[user]]
name = "coleman"
home = "/home/coleman"
groups = ["wheel"]  # if groups don't exist, give better feedback
ssh_public_key = "bkt://ssh-keys/hackbox.pub"

[[service]]
name = "sshd"
status = "restarted"

#[[clone]]
#URL = "https://github.com/tmux/tmux.git"
#dest = "/opt/tmux"
#
#[[clone]]
#URL = "https://github.com/neovim/neovim.git"
#dest = "/opt/neovim"

# look how easy it is to install go 
[[exec]]
script = '''
rm -rf /usr/local/go
wget https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.9.1.linux-amd64.tar.gz


'''

# building neovim
#[[exec]]
#script = "make CMAKE_BUILD_TYPE=RelWithDebInfo"

# installing tmux
# sh autoconf.sh
# ./configure && make
