
packages = ["epel-release", "git", "gcc", "libevent-devel", 
            "automake", "ncurses-devel"]

[bucket.bucket1]
url = "nyc3.digitaloceanspaces.com"
name = "coleman"

[repo.somerepo]
url = "https://github.com/foo/configs.git"

[[group]]
name = "something"

[[group]]
name = "wheel"
passwordless_sudo = true

[[user]]
name = "coleman"
home = "/home/coleman"
groups = ["wheel", "something"]
ssh_public_key = "bucket1://ssh-keys/hackbox.pub"


[[service]]
name = "sshd"
status = "restarted"

[[clone]]
URL = "https://github.com/tmux/tmux.git"
dest = "/opt/tmux"
user = "anxiousmodernman"


# installing tmux
# sh autoconf.sh
# ./configure && make
