secret = 100

[bucket.bucket1]
url = "nyc3.digitaloceanspaces.com"
name = "coleman"

[bucket.bucket2]
url = "nyc3.digitaloceanspaces.com"
name = "coleman2"

[repo.somerepo]
url = "https://github.com/foo/configs.git"

[[user]]
name = "coleman"
home = "/home/coleman"
groups = ["wheel", "something"]
ssh_public_key = "bucket1://ssh-keys/hackbox.pub"


[[group]]
name = "something"
gid = "1001"

[[group]]
name = "wheel"
passwordless_sudo = true

[[service]]
name = "sshd"
status = "restarted"
